---
name: cmpsc-302-spring-2019-practical7
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/www/:
    index.html:
        --fragment "TODO" --count 0 --exact
        --fragment "div class" --count 6 --exact
        --fragment "img src" --count 6 --exact
# --> check the submission image exists
images/gradients_submission.png:
    --exists
src/www/css:
    site.css:
        --exists
        --fragment "TODO" --count 0 --exact
# --> check the number of commits beyond a threshold
--commits 10
# --> check that the linter executes and produces 0 lines of output
--command "htmlhint src/www/index.html" --executes
--command "htmlhint src/www/index.html" --count 1 --exact
--command "htmlhint src/www/index.html" --fragment "no errors found" --count 1 --exact
